[package]
name = "mockphone"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fastrand = "1"
rusqlite = "0.29"
num_cpus = "1.0"
clap = { version = "4", features = ["derive"] }
